### ISSUE TITLE
Ability to run backend separately

### ISSUE THREAD

**Issue by orihomie** [tiangolo/full-stack-fastapi-postgresql#257]
For now its up to 2 days while I'm struggling with postgres docker container and it would've been great if there was any guidelines/ ready compose file to launch them locally and debug that locally.

**Comment by orihomie** [comment]
@tiangolo I appreciate what you did for us all but please, mention somewhere that default values you've put int /backend/app/alembic/env.py

```py
def get_url():
    user = os.getenv("POSTGRES_USER", "postgres")
    password = os.getenv("POSTGRES_PASSWORD", "")
    server = os.getenv("POSTGRES_SERVER", "db")
    db = os.getenv("POSTGRES_DB", "app")
    return f"postgresql://{user}:{password}@{server}/{db}"
```

**Comment by wedwardbeck** [comment]
Do you mean run the DB locally and FastAPI backend locally in a terminal?  for env.py include your .env file and then use python-dotenv:
`from __future__ import with_statement

import os

from alembic import context
from dotenv import load_dotenv
from sqlalchemy import engine_from_config, pool
from logging.config import fileConfig
load_dotenv()
`
Same concept for the backend API which his referenced [here](https://fastapi.tiangolo.com/advanced/settings/).

**Comment by orihomie** [comment]
No, I meant to startup backend project locally via docker compose

**Comment by orihomie** [comment]
that's my yml file

```yml
# Use postgres/example user/password credentials
version: '3.1'
services:

  backend:
    image: backend
    ports:
    - 10088:10088

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_SERVER: server
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

and that what I'm passing to settings

```py
kwargs = {
    'SERVER_NAME': '',
    'SERVER_HOST': 'http://127.0.0.1:10088',

    'PROJECT_NAME': 'CookieBack',

    'SENTRY_DSN': '',
...
    'POSTGRES_SERVER': '127.0.0.1:5432',
    'POSTGRES_USER': 'user',
    'POSTGRES_PASSWORD': 'pwd',
    'POSTGRES_DB': 'db',
    'SQLALCHEMY_DATABASE_URI': 'postgresql://user:pwd@127.0.0.1:5432/db',

    'FIRST_SUPERUSER': 'example@mymail.ru',
    'FIRST_SUPERUSER_PASSWORD': 'example'}

settings = Settings(**kwargs)
```

by
> docker-compose -f stack.yml up --force-recreate --build

Still I'm getting this:

```
backend_1  | WARNING:__main__:Finished call to '__main__.init' after 17.066(s), this was the 18th time calling it.
backend_1  | INFO:__main__:Starting call to '__main__.init', this is the 19th time calling it.
backend_1  | ERROR:__main__:(psycopg2.OperationalError) could not connect to server: Connection refused
backend_1  |    Is the server running on host "127.0.0.1" and accepting
backend_1  |    TCP/IP connections on port 5432?
```

How I've could fix that?
