### ISSUE TITLE
Utils routes returns 403 

### ISSUE THREAD

**Issue by orihomie** [tiangolo/full-stack-fastapi-postgresql#259]
While its ok to get users list while I'm authorized, my backend launched by this yml file:

```yml
version: '3.1'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_SERVER: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default

  queue:
    image: rabbitmq:3

  backend:
    image: backend
    ports:
      - 10088:80
    depends_on:
      - db
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_SERVER=db:5432
      - POSTGRES_DB=example
    build:
      context: .
      dockerfile: backend.dockerfile
    networks:
      - default

  worker:
    image: worker
    depends_on:
      - db
      - queue
#    env_file:
#      - .env
    environment:
      - SERVER_NAME=127.0.0.1:10088
      - SERVER_HOST=http://127.0.0.1:10088
      - SMTP_HOST=mail.overbooru.world
    build:
      context: .
      dockerfile: celeryworker.dockerfile
```

this is what I get:
> "Could not validate credentials"

**UPD** 
Strangely somehow once it worked
```
backend_1  | 172.19.0.1:60238 - "POST /api/v1/utils/test-celery/ HTTP/1.1" 403
queue_1    | 2020-09-09 13:33:50.170 [info] <0.1510.0> accepting AMQP connection <0.1510.0> (172.19.0.6:58248 -> 172.19.0.2:5672)
queue_1    | 2020-09-09 13:33:50.180 [info] <0.1510.0> connection <0.1510.0> (172.19.0.6:58248 -> 172.19.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
backend_1  | 172.19.0.1:60242 - "POST /api/v1/utils/test-celery/ HTTP/1.1" 201
worker_1   | [2020-09-09 13:33:50,191: INFO/MainProcess] Received task: app.worker.test_celery[9e9a074a-8c36-475b-851c-5e0d8b0455d2]  
worker_1   | /usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
worker_1   | absolutely not recommended!
worker_1   | 
worker_1   | Please specify a different user using the --uid option.
worker_1   | 
worker_1   | User information: uid=0 euid=0 gid=0 egid=0
worker_1   | 
worker_1   |   uid=uid, euid=euid, gid=gid, egid=egid,
worker_1   | [2020-09-09 13:33:50,193: INFO/ForkPoolWorker-1] Task app.worker.test_celery[9e9a074a-8c36-475b-851c-5e0d8b0455d2] succeeded in 0.000414699999964796s: 'test task return string'
backend_1  | 172.19.0.1:60248 - "POST /api/v1/utils/test-celery/ HTTP/1.1" 201

```

**UPD 2**
I've tried to generate my own secret key and put a log to a get_current_user method, which now shows that the error is:

> Signature verification failed.

**UPD 3**

I dont know for sure what problem was about but what I did is

0. generated my own secret key and passed that to settings
1. docker system prune -a -f
2. docker-compose up -d

And that worked
