### ISSUE TITLE
How to config the port from 80 to others for backend and front end?

### ISSUE THREAD

**Issue by kongdetai** [tiangolo/full-stack-fastapi-postgresql#27]
I want to use other ports to run backend and frontend, How to config it?
I find all the file, but no idea.

**Comment by tiangolo** [comment]
When you are developing locally, the only one that listens on port 80 is the service (container) named `proxy`. It's a Traefik: https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.dev.ports.yml#L6

Then this `proxy` is in charge of passing the requests to the `backend` or `frontend` depending on the path, taken by these Traefik labels:

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.dev.labels.yml#L10

https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.dev.labels.yml#L16

---

When in production, it uses the `docker-compose.deploy.*.yml` files, they have the equivalent Traefik labels too, in the correct place.

**Comment by Innoviox** [comment]
I am trying to get the proxy to run on port 3000. I have changed all of the files you suggested to have 3000:

```
  proxy:
    ports:
      # - '80:80'
      - '3000:3000'
      - '8090:8080'
```

```
services:
  proxy:
    labels:
      - traefik.frontend.rule=Host:${DOMAIN}
      - traefik.enable=true
      - traefik.port=3000
  backend:
    labels:
      - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc
      - traefik.enable=true
      - traefik.port=3000
      - traefik.tags=${TRAEFIK_TAG}
  frontend:
    labels:
      - traefik.frontend.rule=PathPrefix:/
      - traefik.enable=true
      - traefik.port=3000
      - traefik.tags=${TRAEFIK_TAG}
```
in both `docker-compose.deploy.labels.yml` and `docker-compose.dev.labels.yml`. However, when I load `localhost:3000` in the browser I get "Failed to open page: The server unexpectedly dropped the connection." However, when I navigate to just `localhost:80`, it works fine. Also, `docker-compose logs proxy` has the line:
```
proxy_1          | time="2019-07-31T14:12:41Z" level=info msg="Server configuration reloaded on :80"
```
And `docker-compose logs backend` has the line:
```
backend_1        | INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
```
So it seems that it is still attaching to port 80. Can you recommend any solutions for this?
