### ISSUE TITLE
Psycopg2 Error while deploying to AWS ECS FARGATE 

### ISSUE THREAD

**Issue by umang-mistry-bo** [tiangolo/full-stack-fastapi-postgresql#300]
I am a newbie to docker and backend web development so this issue might seem trivial. I am working on deploying the project to ECS Fargate using ecs-cli. However ecs-cli [does not support](https://docs.amazonaws.cn/en_us/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html) several docker parameters (eg. network). So inorder to deploy it to ECS Fargate, I pushed all the images to AWS Elastic Container Registry and then created a new docker-compose file as follows:

```
version: '3'
services:
    backend:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/backend
        ports:
            - "8888:8888"
        env_file:
            - .env
        environment:
            - SERVER_NAME=${DOMAIN?Variable not set}
            - SERVER_HOST=https://${DOMAIN?Variable not set}
            # Allow explicit env var override for tests
            - SMTP_HOST=${SMTP_HOST}
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker
    celeryworker:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/celeryworker
        env_file:
            - .env  
        environment:
            - SERVER_NAME=${DOMAIN?Variable not set}
            - SERVER_HOST=https://${DOMAIN?Variable not set}
            # Allow explicit env var override for tests
            - SMTP_HOST=${SMTP_HOST?Variable not set}
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker
    
    frontend:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/frontend
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker

    queue:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/rabbitmq
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker
            
    pgadmin:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/pgadmin4
        ports:
            - "5050:5050"
        env_file:
            - .env
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker

    db:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/db
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        logging:
            driver: awslogs
            options: 
                awslogs-group: tutorialv3
                awslogs-region: ap-south-1
                awslogs-stream-prefix: fastapi-docker

    flower:
        image: 123456789123.dkr.ecr.ap-south-1.amazonaws.com/fast-api/flower
        ports:
            - "5555:5555"
        env_file:
            - .env
        command:
            - "--broker=amqp://guest@queue:5672//"
```
        
Along with this there are 2 other files: 

- .env 
- ecs-params.yml (Contains task definition for containers with memory & CPU unit format for which is linked in the guide below)

Using the [guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-fargate.html) I am able to deploy the containers and the cluster reaches a stable state with all containers running. However I am not able to login. Upon checking the logs I came across this for the backend, celeryworker : 
`INFO:__main__:Starting call to '__main__.init', this is the 300th time calling it.
ERROR:__main__:(psycopg2.OperationalError) could not translate host name "db" to address: Name or service not known
`
Since the networks parameter is not supported the containers are not ale to communicate with each other and the backend / celeryworker psycopg2 clients are not able to connect to the db.  

Since all the containers are deployed in a single cluster so they can communicate over localhost and the networking is possible only through awsvpc, is traefik network mandatory  for the project to run on ECS Fargate? Is there a workaround to use 'Networks' parameter in docker compose? Is BACKEND_CORS_ORIGIN preventing the backend container to access the db?

**Comment by haviduck** [comment]
are all the services on the same network?

**Comment by umang-mistry-bo** [comment]
The containers are a part of one cluster so they can interact locally and the default networking is through awsvpc. 

Upon looking at the backend logs it starts the pre_start.sh script, where it throws an error while connecting to the database.

**Comment by haviduck** [comment]
docker needs every service on the same subnet/docker-network/overlay network for servicediscovery.
you also need tcp/udp: 7946 and udp: 4789 open 

https://github.com/aws/amazon-ecs-cli/issues/1005#issuecomment-610487984
and
https://aws.amazon.com/blogs/compute/task-networking-in-aws-fargate/

i use azure myself, and when getting started on this i had alot of issues where the backend prestart tries to populate the db, but your issue is one step before that. 
can properly trouboleshoot service discovery by execing into backend and a lookup/ping to "db" or "tasks.stackname_db". 
i highly recommend portainer for troubleshooting this, helped me out a bunch. 


Good weekend and good luck, hopefully someone knows more about this than i do =)

**Comment by mariuz** [comment]
I would move database to RDS https://aws.amazon.com/rds/postgresql/
also I would replace rabbitmq with redis in celery as broker 

https://aws.amazon.com/redis/

**Comment by mariuz** [comment]
Traefik can be replaced by aws load balancer https://docs.aws.amazon.com/AmazonECS/latest/developerguide/load-balancer-types.html#alb

**Comment by umang-mistry-bo** [comment]
@haviduck I had read that article on task networking. How do I ensure that the containers are using local loopback interface to communicate? I believe that's the only thing that's holding back.

**Comment by umang-mistry-bo** [comment]
@mariuz is replacing Traefik with load balancing imperative ? As [this ](https://aws.amazon.com/blogs/compute/task-networking-in-aws-fargate/)  mentions that awsvpc is the networking mode for deployment on Fargate. And if I do create a load balancer the target group should be pointing to the frontend container ?

**Comment by haviduck** [comment]
> @haviduck I had read that article on task networking. How do I ensure that the containers are using local loopback interface to communicate? I believe that's the only thing that's holding back.

from what i understand, if you exec into backend f. ex and try nslookup, curl or ping 127.0.0.1:5432 it should resolve.  if it does, alias it

**Comment by umang-mistry-bo** [comment]
@haviduck FARGATE does not allow us to exec into container (one of the many restrictions) however I found a work around and changed the POSTGRES_SERVER to 127.0.0.1 and mapped it to the db port. Since all the containers can communicate using local loopback, backend was finally able to connect to the database. It would be much easier to debug if we could exec into the containers on FARGATE. I am a newbie with deployment so took me some trial and error to figure it out. I am closing this issue now. Thank for your help.

**Comment by mariuz** [comment]
Also seems that AWS lauched rabbitmq service so no need to replace it with redis 

https://aws.amazon.com/blogs/aws/amazon-mq-update-new-rabbitmq-message-broker-service/

**Comment by cook1emonstr** [comment]
For anyone who comes by here looking for AWS ECS Fargate help. I had to do the following at a high level to get it to work, but I am skipping over a lot of the AWS/ECS/Fargate setup, requirements and commands (such as ecs-params.yml etc), you'll need to read up on those because there is quite a bit that you need to do to prepare...

The VPC I created has 4 subnets, 2 public and 2 private. I also went with an ALB instead of traefik. The private subnets can reach the internet via NAT gateways. I deployed my containers into the private subnets, making them only accessible by the ALB. 


1. I separated the frontend container into its own task definition. Having frontend and backend on the same task definition will cause a port conflict because both try to listen on 80 via their respective web servers, all containers in the same Fargate task definition use the same local loopback. 
2. You'll need to create two new docker-compose files that use version 3 (The template uses version 3.3 is not supported.), one for just the frontend container and one for everything else. 
3. As stated above Fargate tasks don't have the same way to resolve via service discovery like docker does and instead share the same loopback. So if PSQL, rabbitmq, and the other backend containers are all on the same task they can talk to each other via `localhost`. Therefore you have to make some code changes.  Set `POSTGRES_SERVER` to `localhost` in `.env`, and change the celery instantiation in `backend/app/app/core/celery_app.py ` to `celery_app = Celery(broker="amqp://guest:guest@localhost:5672/")` 
4. My ALB has two listeners (80,443) with two target groups (a backend and frontend target group). The ALB sends traffic to `/api/*`, `/docs`, and `/redoc` to the backend target group, and the rest defaults to the front end target group. 
5. I created new repos in ECR, then built my new images using the ECR urls as prefixes so that docker can push to ECR for you (no need to do it for the publicly available images)
6. I launched my two services under one cluster using `ecs-cli compose service up`, using --target-groups so that my ALB would send traffic to each service accordingly

So here are some sample compose files, in these samples you'll need to set a `DOCKER_REGISTRY` env var somewhere that is the URL of your ECR registry. 

*Backend compose*
```
version: "3"
services:

  backend:
    image: '${DOCKER_REGISTRY?Variable not set}/${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: backend

  celeryworker:
    image: '${DOCKER_REGISTRY?Variable not set}/${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST?Variable not set}
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: celeryworker

  queue:
    image: rabbitmq:management
    ports:
      - "5672:5672"
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: queue

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: pgadmin

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: db

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    command:
      - "--broker=amqp://guest@queue:5672//"

volumes:
  app-db-data:
```
*Frontend Compose*
```
version: "3"
services:
  frontend:
    image: '${DOCKER_REGISTRY?Variable not set}/${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: fast-api
        awslogs-region: us-west-2
        awslogs-stream-prefix: frontend
```
