### ISSUE TITLE
[question] how is that localhost can work on HTTP ?

### ISSUE THREAD

**Issue by gerazenobi** [tiangolo/full-stack-fastapi-postgresql#363]
Hi there, 

I was intrigued to know how is that we can use HTTP when running the project locally at localhost ? In other words, how is that all the HTTPS (redirects, etc) part is not kicking in ? (note that I am good with that and don't want it to kick in, just want to understand a bit more about Traefik and which setting/s in the project is/are allowing this behaviour)

Cheers.

**Comment by NMisko** [comment]
As far as I know `docker.compose.override.yml` overwrites the proxy service to not use https.

**Comment by gerazenobi** [comment]
Going through the docker compose files again after seen your comment to double check I had not missed something: I think I might have found why: it is not that the `docker.compose.override.yml` overrides any of the HTTPS stuff (like redirection, etc), it is just that all that part is defined under docker swarm deploy labels:

```yaml
    deploy:
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK?Variable not set}
```
which are ignored if running the stack outside swarm (the case for local development). 

> Specify configuration related to the deployment and running of services. This only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up and docker-compose run.

The labels in `docker.compose.override.yml` are just _regular_ ones at the service declaration level.

Easily to get confused with the output of `docker-compose config` for the untrained eye (having not worked with swarm before I was reading them as regular labels ... )
