### ISSUE TITLE
How to edit docker-compose.yml to add new docker container?

### ISSUE THREAD

**Issue by yusuke2930** [tiangolo/full-stack-fastapi-postgresql#382]
I want to add docker container for nuxt.js.
So I edited docker-compose .yml as below.
but not working

```
frontend_client:
    image: '${DOCKER_IMAGE_FRONTEND_CLIENT?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend_client
      args:
        FRONTEND_CLIENT_ENV: ${FRONTEND_CLIENT_ENV-production}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
        - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
        - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=81
```
