### ISSUE TITLE
[Question] WebSocket config example

### ISSUE THREAD

**Issue by plankter** [tiangolo/full-stack-fastapi-postgresql#54]
Could you please provide an example of how to configure access to WebSockets? For instance, to the following endpoint:

```
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    await websocket.send_text(f"WebSocket client connected")
```

I could't connect to the endpoint from the client app, getting `Error during WebSocket handshake: Unexpected response code: 200`. I suppose, either Traefik or Nginx configs should be changed.

**Comment by DrNickMartin** [comment]
I'm having exactly the same issue - any steer on how to fix this would be great.

**Comment by tiangolo** [comment]
Thanks for the discussion here!

I would actually prefer to keep this project template more or less simple, I also don't think WebSockets are a good solution for most of the cases where people try to use them, they are great for things that need them, but most of the cases are fine with plain HTTP that already has a lot of things in place. For example, a browser can't set headers in a WebSocket connection.

Using WebSockets requires a heavy investment into re-implementing many things that are already implemented in a "standard" way in HTTP, so I would prefer not to encourage people to go that route to end up at a dead-end later.

But for the advanced use cases that actually need WebSockets, there's the docs section on the main website with all the info.

**Comment by plankter** [comment]
I managed to make WebSockets work properly, so i suppose i can close the issue. WebSockets are quite useful in my scenario, as i need to notify a browser client when a long-running Celery worker finishes its processing, but i agree that it is a very specific use case.

**Comment by jceyrac** [comment]
Hi @plankter , how did you manage to make the websocket work?
I've added your WebSocket example in `main.py`:

```python
from fastapi import FastAPI, WebSocket
from starlette.middleware.cors import CORSMiddleware

from app.api.api_v1.api import api_router
from app.core.config import settings

app = FastAPI(
    title=settings.PROJECT_NAME, openapi_url=f"{settings.API_V1_STR}/openapi.json"
)

# Set all CORS enabled origins
if settings.BACKEND_CORS_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[str(origin) for origin in settings.BACKEND_CORS_ORIGINS],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

app.include_router(api_router, prefix=settings.API_V1_STR)


# ws://localhost:8080/ws
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    await websocket.send_text(f"WebSocket client connected")
```

and tried updating the docker-compose.override.yml and docker-compose.yml files with the traefik labels:

```yml
backend:
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app:/app
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /start-reload.sh
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`) || PathPrefix(`/ws`)
      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80
      - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc,/ws
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}
```

but I still get connection error to `ws://localhost:8080/ws` :(

<img width="711" alt="Capture d’écran 2020-11-09 à 23 59 54" src="https://user-images.githubusercontent.com/62670612/98606590-cb633b80-22e7-11eb-9719-c193293b713e.png">

When implementing the same WebSocket in an other fastapi app only project it works fine so I guess it's a config issue in the backend somewhere but I know where to look unfortunately... Any idea?
